mergeable:
  pull_requests:
    title:
      must_exclude: {regex: wip, message: 'This PR is work in progress.'}
    label:
      must_exclude: {regex: wip, message: 'Custom message. This PR is work in progress.'}
    description:
      must_exclude: {regex: WIP, message: 'Custom message. wip'}