version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: approvals
        required:
          reviewers: [ 'shineFakeAccount' ] # list of github usernames required to review
          message: 'Custom message...'