version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: or
        validate:
          - do: or
            validate:
              - do: title
                must_exclude:
                  regex: 'must_be_excluded_text'
                must_include:
                  regex: 'must_be_included_text'
              - do: label
                or:
                  - must_include:
                      regex: 'must_be_included_text'
                  - begins_with:
                      regex: 'begins_with_text'
                begins_with:
                  match: 'begins_with_text'
          - do: label
            or:
              - must_include:
                  regex: 'must_be_included_text'
              - begins_with:
                  regex: 'begins_with_text'
            begins_with:
              match: 'begins_with_text'

