mergeable:
  pull_requests:
    stale:
      # A comment is psoted when a PR is stale
      days: 20

    title:
      # Block if the title contains an of
      must_exclude: 'wip|poc'
      # Block if title does not match any of
      must_include: '^(feat|doc|chore|fix|refactor|test)\(\w+\): .+$'

    label:
      # Block if it any of these labels are present
      must_exclude: 'dontmerge|wip|blocked'

    description:
      # Block if no description
      no_empty:
        enabled: true