mergeable:
  pull_requests:
    stale:
      # number of days for a PR to be considered stale. A comment is posted when it is stale.
      days: 20
      # Optional property. When not specified the default is used. The default message is:
      # There haven't been much activity here. This is stale. Is it still relevant? This is a friendly reminder to please resolve it. :-)
      message: 'This is PR is stale. Please follow up!'
    label:
      must_include:
        regex: 'staging|UAT OK'
        message: 'Needs to be merged on Staging and have UAT complete'
      must_exclude:
        regex: 'work in progress|do not merge|experimental|proof of concept|breaking change'
        message: "This PR is still being worked on. OR it has a breaking change. Talk to another human before merging"
    title: 'wip|dnm|exp|poc'
    description:
      no-empty: true