version: 2
mergeable:
  - when: pull_request.open, pull_request_review.*
    validate:
      - do: approvals
        or:
          - required:
              reviewers: ['jusx']
          - required:
              reviewers: ['shine2lay']