version: 2
mergeable:
  - when: issues.*
    validate:
      - do: label
        must_include:
          regex: test
    pass:
      - do: comment
        payload: >
          Second Comment
  when: issue.*
    validate:
      - do: label
        must_include:
          regex: test
    pass:
      - do: comment
        payload: >
          Second Comment
