version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: project
        must_include:
          regex: 'Infrastructure'
          message: 'PR is in the Infrastructure project.'
      - do: label
        must_exclude:
          regex: 'infrastructure'
          message: 'PR does not have the Infrastructure label.'
    fail:
      - do: checks
        status: 'success'
        payload:
          title: 'Infrastructure project rule is not applicable.'
          summary: "The Mergeable rule enforcing correct labeling on Infrastructure project issues does not apply here."
    pass:
      - do: labels
        labels: [ 'infrastructure' ]