version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: title
        must_exclude:
          regex: 'wip|work in progress'
          message:
            pass: 'Good: `wip|work in progress` is not in the title.'
            fail: '`wip|work in progress` was found in the title'
    pass:
      - do: checks
        status: success
    fail:
      - do: checks
        status: failure