version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: project
        must_include:
          regex: /\b(?:(?:Jan|Febr)uary|March|April|June|(?:Ma|Jul)y|August|(?:Septem|Octo|Novem|Decem)ber)\s{1}?(?:20\d{2})\b/
          message: PR must be in a sprint project to be merged.
    fail:
      - do: checks # default fail case
        status: 'failure' # Can be: success, failure, neutral, cancelled, timed_out, or action_required
        payload:
          title: 'Mergeable Run have been Completed!'
          summary:  |
            ### Status: {{toUpperCase validationStatus}}
                 Here are some stats of the run:
                 {{validationCount}} validations were ran.
                 {{passCount}} PASSED
                 {{failCount}} FAILED
          text: |
            {{#each validationSuites}}
                #### {{{statusIcon status}}} Validator: {{toUpperCase name}}
                {{#each validations }} * {{{statusIcon status}}} ***{{{ description }}}***
                       Input : {{{details.input}}}
                       Settings : {{{displaySettings details.settings}}}
                       {{/each}}
                {{/each}}

