mergeable:
  pull_requests:
    title:
      must_include:
        message: 'Title must include a pivotal story tag and optionally an action (e.g. Delivers or Finishes)'
        regex: ^\[(Delivers \#\d{7,}|Finishes \#\d{7,}|\#\d{7,})\]