version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: size
        lines:
          max:
            count: 2
          total:
            count: 1
          deletions:
            count: 1