version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: approvals
        required:
          reviewers: ['shineTest']
    fail:
      - do: request_review
        reviewers: ['shineTest']