version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        and:
          - begins_with:
              match: 'begins_with_text'
          - ends_with:
              match: 'ends_with_text'
        or:
          - must_include:
              regex: 'must_be_included_text'
          - begins_with:
              match: 'begins_with_text'
        must_exclude:
          regex: 'must_be_excluded_text'
        must_include:
          regex: 'must_be_included_text'
        begins_with:
          match: 'begins_with_text'
        ends_with:
          match: 'ends_with_text'
      - do: assignee
        and:
          - max:
              count: 4
          - min:
              count: 1
        or:
          - max:
              count: 4
          - min:
              count: 1
        required:
          reviewers: ['shine2lay', 'shinelay']
        max:
          count: 4
        min:
          count: 1
        no_empty:
          enabled: true
      - do: size
        lines:
          max:
            count: 2
      - do: label
        and:
          - begins_with:
              match: 'begins_with_text'
          - must_include:
              regex: 'must_be_included_text'
        or:
          - must_include:
              regex: 'must_be_included_text'
          - begins_with:
              match: 'begins_with_text'
        must_exclude:
          regex: 'must_be_excluded_text'
        must_include:
          regex: 'must_be_included_text'
        required:
          reviewers: ['shine2lay', 'shinelay']
        begins_with:
          match: 'begins_with_text'
        ends_with:
          match: 'ends_with_text'
        max:
          count: 4
        min:
          count: 1
        no_empty:
          enabled: true
      - do: description
        and:
          - begins_with:
              match: 'begins_with_text'
          - ends_with:
              match: 'ends_with_text'
        or:
          - must_include:
              regex: 'must_be_included_text'
          - begins_with:
              match: 'begins_with_text'
        must_exclude:
          regex: 'must_be_excluded_text'
        must_include:
          regex: 'must_be_included_text'
        begins_with:
          match: 'begins_with_text'
        ends_with:
          match: 'ends_with_text'
        no_empty:
          enabled: true
      - do: dependent
        files: ['abc.js', 'def.js']
      - do: milestone
        and:
          - begins_with:
              match: 'begins_with_text'
          - ends_with:
              match: 'ends_with_text'
        or:
          - must_include:
              regex: 'must_be_included_text'
          - begins_with:
              match: 'begins_with_text'
        must_exclude:
          regex: 'must_be_excluded_text'
        must_include:
          regex: 'must_be_included_text'
        begins_with:
          match: 'begins_with_text'
        ends_with:
          match: 'ends_with_text'
        no_empty:
          enabled: true
      - do: project
        must_exclude:
          regex: 'must_be_excluded_text'
        must_include:
          regex: 'must_be_included_text'
        begins_with:
          match: 'begins_with_text'
        ends_with:
          match: 'ends_with_text'
        no_empty:
          enabled: true
      - do: approvals
        max:
          count: 4
        min:
          count: 1
        required:
          reviewers: ['shineTest', 'shinelay']
          owners: true
      - do: or
        validate:
          - do: title
            must_exclude:
              regex: 'must_be_excluded_text'
            must_include:
              regex: 'must_be_included_text'
          - do: label
            or:
              - must_include:
                  regex: 'must_be_included_text'
              - begins_with:
            begins_with:
              match: 'begins_with_text'