mergeable:
  pull_requests:
    title:
      must_exclude:
        regex: 'wip'
    label:
      must_include:
        regex: 'Label A'
      must_exclude:
        regex: 'Label B'
    description:
      no_empty:
        enabled: true