mergeable:
  pull_requests:
    stale:
      # number of days for a PR to be considered stale. A comment is posted when it is stale.
      days: 1
      message: 'This is PR getting stale. Please follow up!  This is a friendly reminder to please resolve it. :-)'
    title:
      must_exclude:
        regex: 'wip'
        message: 'This PR is work in progress.'

    label:
      must_exclude:
        regex: 'wip'
        message: 'This PR is work in progress.'

    approvals:
      min: 2
      message: 'Waiting on approvals...'
      required:
        reviewers: [ GLJeffery, kevnm67 ]   # list of github usernames required to review
        message: 'Now we wait...'