version: 2
mergeable:
  - when: pull_request.*
    validate:
      # validate title
      - do: description
        and:
          - must_xclude:
              regex: 'must_exclude'
          - must_include:
              regex: 'must_include'
      - do: title
        must_include:
          regex: 'test'