version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: label
        and:
          - must_include:
              regaex: 'test plan: no'
          - must_include:
              regesx: 'test'

