mergeable:
  pull_requests:
    title:
      must_include:
        regex: '^STAR-\d{4,8}: .*'
        message: 'Title must be in the format - STAR-12345: Description of PR'
    description:
      no-empty: false