version: 2
mergeable:
  - when: issues.*
    validate:
      - do: label
        must_include:
          regex: test
    pass:
      - do: comment
        payload:
          body: >
            First Comment
  - when: issues.*
    validate:
      - do: label
        must_include:
          regex: test
    pass:
      - do: comment
        payload:
          body: >
            Second Comment
