version: 2
mergeable:
  # Runs when any pull request event is fired (eg. opened, edited, etc)
  - when: pull_request.*
    validate:
      - do: title
        # Block if the title contains an of
        must_exclude:
          regex: 'wip|poc'
        # Block if title does not match any of
        must_include:
          regex: '^(feat|doc|chore|fix|refactor|test)\(\w+\): .+$'
      - do: label
        # Block if it any of these labels are present
        must_exclude:
          regex: 'dontmerge|wip|blocked'
      - do: description
        # Block if no description
        no_empty:
          enabled: true

  # Runs on an interval
  - when: schedule.repository
    validate:
      - do: stale
        # A comment is posted when a PR is stale
        days: 7
        type: pull_request
    pass:
      - do: comment
        payload:
          body: This is rotting. Either update and merge or close it.