version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: approvals
        required:
          reviewers: [ 'shineTest' ] # list of github usernames required to review
          assignees: true # Optional boolean. When true, PR assignees are made required reviewers.
          message: 'Custom message...'