mergeable:
  pull_requests:
    stale:
      days: 14
      message: "This is PR is stale. Please follow up!"
    title:
      must_include:
        message: "Title must have prefixes for the following: (feat), (doc), (fix)"
        regex: ^\\(feat\\)|^\\(doc\\)|^\\(fix\\)