version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: or
        validate:
          - do: label
            must_include:
              regex: test
          - do: title
            must_include:
              regex: wip

