version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: dependent
        changed:
          file: abc.js
          files: ['package-lock.json', 'yarn.lock']
    fail:
      - do: comment
        payload:
          body: >
            @shine2lay mention test